[package]
name = "actix-web-idempotency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4"
uuid = "1.4"
chrono = "0.4"
futures-util = "0.3"
serde = "1"
serde-json = "1"
